nelmio_api_doc:
    documentation:
        host: '%env(BASE_URL)%'
        info:
            title: Quotes API
            description: API for shouting quotes
            version: 1.0.0
    areas:
        path_patterns:
            - ^/shout
