version: "2"
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379"
  php:
    container_name: php
    build: ./docker/php-fpm
    entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mysql:3306", "-wait" ,"tcp://rabbitmq:5672", "-timeout", "20s"]
    command: ["/usr/sbin/php-fpm7", "--nodaemonize"]
    volumes:
      - .:/home/ipresence/quotes_api
    env_file:
      - ./docker/.env
    links:
      - redis
      - mysql
      - rabbitmq
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes_from:
      - php
    env_file:
      - ./docker/.env
    links:
      - php
  mysql:
    container_name: mysql
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    env_file:
        - ./docker/.env
        - ./.env
    ports:
      - "3306:3306"
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    env_file:
      - ./docker/.env
    ports:
      - "5672"
      - "15672"
  worker:
    build: ./docker/worker
    volumes:
      - .:/home/ipresence/quotes_api
    env_file:
      - ./docker/.env
    links:
      - redis
      - rabbitmq